app/controllers/pages_controller.rb, app/views/pages/home.html.erb
=> methode de carte pour home

.gitignore, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/shared/_card_index.html.erb, app/views/shared/_card_show.html.erb
=> Cards render

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, db/migrate/20211124140452_change_column_to_bigint.rb, db/schema.rb
Debug column "color_tags_api_file_id" dans le shema de db
=> debug column "color_tags_api_file_id"

app/controllers/artworks_controller.rb
fixedviewindex + add method ind dans le artwork controller
=> fixedviewindex + add method ind dans le artwork controller

app/controllers/upvotes_controller.rb, app/views/artworks/show.html.erb, test/controllers/upvotes_controller_test.rb
Creation du controller de upvotes mais sans la limite de vote par semaine pour le moment
=> controller upvotes created

app/controllers/upvotes_controller.rb, app/views/artworks/show.html.erb
controler vote unique par utilisateur fonctionnel et ajout du lien sur la carte de la show
=> controler vote unique par utilisateur fonctionneml

app/controllers/artwork_prices_controller.rb, app/controllers/artworks_controller.rb, app/views/artworks/show.html.erb, test/controllers/artwork_prices_controller_test.rb
Creation du controller Artwork_prices + debug des routes liés a ce controlleur et verification de la possibilité d'estimer un seul prix par article
=> Controllerprice

app/views/artworks/show.html.erb
=> debug done

app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb, app/views/shared/_card_index.html.erb, config/routes.rb
-Dans un premier temps recrifiacation du nommage dans route du nommage de celle de dashboard
-creation de la méthode dashboard dans pages_controller
-creation de la view du dashboard 
NOTE IMPORTANTE: le score n'etant pas calculer encore dans le fichier card_index qui se trouve dans le dossier share j'ai du commenter deux ligne qu'il faudra remettre. 
-Ligne 9 et ligne 11 de ce même fichier. 
cheers
=> creation de la route dashboard + methode

Gemfile, Gemfile.lock, app/controllers/artworks_controller.rb, app/controllers/pages_controller.rb, app/views/artworks/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_card_index.html.erb, app/views/shared/_navbar.html.erb
seach bar fonctionne + la show qui affiche plus les trucs chelou et les infos en trop soont commentéq
=> search ok + show sans truc chelou + qq autre details

app/controllers/artworks_controller.rb, app/views/artworks/show.html.erb, config/routes.rb
lartiste peut ajouter l'url de son artwork sur la market place, le boutonn redirect enverra direct vers
=> Marketplace url

app/views/shared/_card_index.html.erb
=> remise en place d un grand if

app/controllers/artworks_controller.rb, app/services/get_color_tags.rb, app/services/upload_file_to_api.rb
=> deuxieme modif pour personnaliser l erreur dupload

app/controllers/artworks_controller.rb
Reparation du conflit precedent sur la page de rendu en cas d'erreur 500
=> reparation du conflit de la precedente branche

app/views/artworks/show.html.erb, app/views/shared/_card_index.html.erb
Ajout du nom de l'artiste dans l'index a la place de la description et ajout en plus de l'artiste sur la shwo d'une carte
=> Artistapparition

app/controllers/artworks_controller.rb
=> bzrre de recherche done

app/views/pages/home.html.erb
Liens clickable fait sur la home
=> lien clickable

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
=> show des artistes du mois plus positionnement

app/assets/stylesheets/pages/_home.scss
Changment precedent rectifié concernant la taille, la positon et la couleur du h1 "Uniqueness artist of the month"
=> correction home artist of month

app/views/artworks/show.html.erb
=> fixed show upvote

app/views/artworks/show.html.erb
Lien clickable pour le noùm de l'artsite
=> artist name added

app/assets/stylesheets/components/_buttons.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
=> putain de bouton de merde

app/views/layouts/application.html.erb
Title tag de la checklist fait ---> "Uniqueness, the digital gallery that compares and connects your work with the world"
=> title tag set

app/views/artworks/show.html.erb
Application  des tags metas dans la show de artwork afin de pouvoir partager un lien avec la show d'un artwork
=> last update

app/views/artworks/show.html.erb
Suppression d'un caractère "b" qui se baladait sur la show ???
=> suppression

app/assets/stylesheets/components/_buttons.scss, app/views/artworks/show.html.erb
Rectification du positionnement ainsi que la hauteur du bouton upvote
=> remise en place du bouton

app/views/artworks/show.html.erb
Remise en place du prix pour un artwork
=> controller price
